# Combined Docker Configuration File
# This file contains both docker-compose and Dockerfile configurations in one file
# To use this file: 
# 1. Copy this file to docker-compose.yml
# 2. Run 'docker-compose up'

version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: food_monitoring_postgres
    environment:
      POSTGRES_DB: food_monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    # The following configuration replaces the need for a separate Dockerfile
    # It builds the application container directly from this file
    build:
      context: .
      dockerfile: |
        FROM openjdk:17-jdk-slim
        VOLUME /tmp
        COPY build/libs/*.jar app.jar
        ENTRYPOINT ["java","-jar","/app.jar"]
    container_name: food_monitoring_app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/food_monitoring
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234

volumes:
  pgdata:
