server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/foodmonitoring
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      indent-output: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt:
  secret: U29tZVNlY3JldEtleUluQmFzZTY0MTIzNDU2
  expiration: 3600000
