server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/food_monitoring
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    drop-first: true
